### ISSUE TITLE
Compiling assistance 

### ISSUE THREAD

**Issue by trader418** [Lyliya/RocketStats#17]
Hi,

Love the plugin. Just having some trouble compiling it from the source.

I will paste my build errors below.

```
RocketStats.cpp(32): error C2039: 'GetBakkesModPath': is not a member of 'GameWrapper'
..\..\BakkesModSDK\include\bakkesmod/wrappers/GameWrapper.h(37): note: see declaration of 'GameWrapper'
RocketStats.cpp(32): error C2672: 'std::make_shared': no matching overloaded function found
RocketStats.cpp(36): error C2039: 'GetBakkesModPath': is not a member of 'GameWrapper'
..\..\BakkesModSDK\include\bakkesmod/wrappers/GameWrapper.h(37): note: see declaration of 'GameWrapper'
RocketStats.cpp(36): error C2672: 'std::make_shared': no matching overloaded function found
RocketStats.cpp(40): error C2039: 'GetBakkesModPath': is not a member of 'GameWrapper'
..\..\BakkesModSDK\include\bakkesmod/wrappers/GameWrapper.h(37): note: see declaration of 'GameWrapper'
RocketStats.cpp(40): error C2672: 'std::make_shared': no matching overloaded function found
RocketStats.cpp(46): error C2039: 'GetBakkesModPath': is not a member of 'GameWrapper'
..\..\BakkesModSDK\include\bakkesmod/wrappers/GameWrapper.h(37): note: see declaration of 'GameWrapper'
RocketStats.cpp(46): error C2672: 'std::make_shared': no matching overloaded function found
RocketStats.cpp(674): error C2039: 'GetBakkesModPath': is not a member of 'GameWrapper'
..\..\BakkesModSDK\include\bakkesmod/wrappers/GameWrapper.h(37): note: see declaration of 'GameWrapper'
RocketStats.cpp(674): error C2664: 'std::basic_ofstream<char,std::char_traits<char>>::basic_ofstream<std::experimental::filesystem::v1::path>(const std::experimental::filesystem::v1::path &,std::ios_base::openmode,int)': cannot convert argument 1 from 'int' to 'const std::experimental::filesystem::v1::path &'
RocketStats.cpp(674): note: Reason: cannot convert from 'int' to 'const std::experimental::filesystem::v1::path'
RocketStats.cpp(674): note: use of undefined type 'std::experimental::filesystem::v1::path'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\fstream(45): note: see declaration of 'std::experimental::filesystem::v1::path'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\fstream(1028): note: see declaration of 'std::basic_ofstream<char,std::char_traits<char>>::basic_ofstream'
```

If you could point me in the right direction with these errors I would really appreciate it. I'm using the latest bakkesmod sdk from github and using the following to build:

`cl /LD -I ..\..\BakkesModSDK\include\ ..\..\BakkesModSDK\lib\pluginsdk.lib RocketStats.cpp`

Thanks for your help :)

**Comment by Larsluph** [comment]
Well we're using the SDK included with the bakkesmod injector and for the full compilation we're using the MSVC compiler.

I can only suggest you to do the same.

**Comment by trader418** [comment]
Okay thanks. I am already using MSVC.

I have tried with the included sdk with the injector but unfortunately still having the same issues.

Thanks for trying to help. I'll close the issue as obviously its an environment problem not a code problem.

But if you ever run into the same issue and find a fix It would be great if you could update this issue.

Just for extra info when I start the x64 native tools command prompt window, it says this is the version im running:

Visual Studio 2019 Developer Command Prompt v16.11.2

Just in case it is version related.

**Comment by Larsluph** [comment]
Good news! I just remembered I got a similar issues with path not being recognized etc by the compiler.

For them to work we had to change the C++ Language Standard from "ISO C++14 Standard" to "ISO C++17 Standard (/std:c++17)"
I tried to recompile it with the C++14 and it printed out the same errors as you.

**Comment by trader418** [comment]
Thanks for that, I can confirm thats resolved the issues and compiles fine with that.
