### ISSUE TITLE
I get game stutter while using this plugin

### ISSUE THREAD

**Issue by hankgames** [Lyliya/RocketStats#18]
A fresh install of bakkesmod runs the game without any issues. As soon as this plugin is added though, I get random game and frame stutters. I watched the in-game performance graphs and only saw spikes in those two categories. What should I do/disable to make this run smoothly again?

**Comment by Larsluph** [comment]
Have you tried with other plugins or just with RS ?

**Comment by hankgames** [comment]
I've tried with other plugins and no stutter until this plugin is installed. If that wasn't the case though what would be recommended? To cover all my bases here I'd like to try all my options. This plugin is too good for me to give up on using it just because I get game stutter, so I want to try getting this to work properly.

**Comment by Larsluph** [comment]
The stutters appear in a match or everywhere ?

**Comment by hankgames** [comment]
I haven't noticed them in the main menu, but in training and matches, I notice them.

**Comment by Larsluph** [comment]
In that case, try hiding the menu while in game (it's in the config menu)

**Comment by hankgames** [comment]
I'll give that a shot.

**Comment by hankgames** [comment]
Although the overlay is hidden while in game, the stutter continues.

**Comment by Larsluph** [comment]
Can you send me your build ?
(CPU, RAM, GPU, HDD / SSD, ethernet / WiFi)

**Comment by hankgames** [comment]
CPU: AMD Ryzen 9 5950x
RAM: 32 GB DDR4
GPU: GTX 1080
SSD: 4TB
Ethernet: 500+ Down, ~23 Up

**Comment by Larsluph** [comment]
Are you using the v1 or v2 overlay ?

**Comment by hankgames** [comment]
V2 I think. Whichever one is default is the one I use.

**Comment by Larsluph** [comment]
The one in the `README.md` file?

**Comment by hankgames** [comment]
Yes.

**Comment by Larsluph** [comment]
Can you try with the v1 to see if stutters come from the images?

**Comment by hankgames** [comment]
I'll give it a shot.

**Comment by hankgames** [comment]
In training, still get a stutter.

**Comment by hankgames** [comment]
I have bakkesmod console open during training, I see a stutter in the performance graph, but nothing in the console. so I don't know.

**Comment by Larsluph** [comment]
Well I really don't understand because my PC is way worse than yours and it runs fine with ultra video settings.

**Comment by hankgames** [comment]
The joys of custom rigs and windows I guess.

**Comment by Larsluph** [comment]
How many plugins do you have loaded ?

**Comment by hankgames** [comment]
Only default, no extras

**Comment by Larsluph** [comment]
Try deactivating "Shader Cache" for Rocket League in the NVIDIA Control Panel:
Manage 3D settings > Program settings > Rocket League > Shader Cache > Off
Restart Rocket League and tell me if it changed anything.

**Comment by hankgames** [comment]
👌🏻

**Comment by hankgames** [comment]
Nope, that didn't work either.

**Comment by Larsluph** [comment]
Well, I've looked in the source but I can't find code that can be optimized unfortunately.

**Comment by hankgames** [comment]
Damn, alright.
