### ISSUE TITLE
MMRchange over session?

### ISSUE THREAD

**Issue by RandomNerd1** [Lyliya/RocketStats#22]
Just started using this, it seems like the MMRchange field is only showing the MMR change for the most recent game. I'd like to see how my MMR has changed over the whole session. Is this possible?

I'm using mode "GameMode" and theme "Default", by the way.

**Comment by Arubinu** [comment]
Yes, check the Wiki.
A bug is however present on certain values, there will be an update by the end of the week.

Consider using the Discord to ask your questions.
