### ISSUE TITLE
Feature Request: Add the ability to see the MMR required to reach the next rank

### ISSUE THREAD

**Issue by nefariouslegion** [Lyliya/RocketStats#24]
Hi, 
I'm making a feature request. I was wondering if you could add the ability to see either the amount of MMR still needed to reach the next rank or even just something that shows the total required MMR to reach the next rank?

Up until recently I was using the RankViewer plugin for this but it has started crashing my game some of the time now so I can no longer use it. But I think the feature it provided would also be perfect for the Rocket Stats plugin.

**Comment by Larsluph** [comment]
Thanks for the request, but unfortunately this feature won't be added.
As you said, other plugins already provide this feature.

**Comment by nefariouslegion** [comment]
Yeah but the RankViewer plugin seems to cause crashes now and hasn't been updated in ages. I don't know of another plugin that provides this feature
________________________________

**Comment by Larsluph** [comment]
No other plugin provide this feature because it's awful to setup xD.

And just in case, do you have AlphaConsole installed ?

**Comment by nefariouslegion** [comment]
Ah I didn't realize it was that bad to set up lol.

Yeah I do have AlphaConsole
________________________________
