### ISSUE TITLE
RocketStats_CarTouches

### ISSUE THREAD

**Issue by Roninini** [Lyliya/RocketStats#25]
These stats appear to not work.  We did some testing and can't figure out what these measure.  We had assumed that these were measuring bumps.

RocketStats_CarTouches
RocketStats_CarTouchesCumul
RocketStats_CarTouchesMatch

**Comment by Arubinu** [comment]
CarTouches is an Accolade.
I don't remember exactly its activation conditions, but it is only activated at the bump

**Comment by Larsluph** [comment]
These variables count the number of times that you were awarded with the "CarTouches" accolade at the end of a match (on top of the final scoreboard)
