### ISSUE TITLE
Suggestion: Merge Arubinu/RocketStats_themes to this Repository

### ISSUE THREAD

**Issue by joshua-small** [Lyliya/RocketStats#27]
I suggest merging the contents of [Arubinu/RocketStats_themes](https://github.com/Arubinu/RocketStats_themes) into [Lyliya/RocketStats/bakkesmod/data/RocketStats/RocketStats_themes](https://github.com/Lyliya/RocketStats/bakkesmod/data/RocketStats/RocketStats_themes), and to add the preview screenshots for each of the themes to the README or the Wiki section for Themes.

An alternative could be to have [Arubinu/RocketStats_themes](https://github.com/Arubinu/RocketStats_themes) added as a submodule in [Lyliya/RocketStats/bakkesmod/data/RocketStats/RocketStats_themes](https://github.com/Lyliya/RocketStats/bakkesmod/data/RocketStats/RocketStats_themes).

**Comment by Arubinu** [comment]
It would weigh down the plugin, which we don't want.
But one day maybe there will be the possibility to easily add themes.
For the moment we don't have many participations or requests on this side, which would be a waste of money (for a website for example).

**Comment by joshua-small** [comment]
The plugin installs very quickly for me, and now I see that the original plugin is roughly 3 MB and the additional themes add ~25 MB to a ~3 MB plugin.

I was also going to suggest including a `/bakkesmod/data/RocketStats/RocketStats_overlay` directory, using the contents from [Arubinu/RocketStats_overlay](https://github.com/Arubinu/RocketStats_overlay), but I imagine that the same logic applies here.

On that topic, can we add the overlays documentation from [Arubinu/RocketStats_overlay](https://github.com/Arubinu/RocketStats_overlay) to this wiki?

**Comment by Arubinu** [comment]
This is way too much, I doubt BakkesMod allows such a heavy plugin.

As for RocketStats_overlay, it is abandoned because the Websocket has arrived. This one is archived but there are sample clients in the plugin that allow you to have real-time information without continuously writing files to disk.
On the other hand, we would like users to make beautiful overlays using these features.
