### ISSUE TITLE
Feature: show in training

### ISSUE THREAD

**Issue by maggaou** [Lyliya/RocketStats#28]
Currently supported visibility settings are 'show in menu', 'show while in-game' and 'show on scoreboard'. There is a config file bakkesmod\cfg\default_training.cfg but I'm not sure can this be used to run any command before training sessions.

I'm sorry if feature requests are not suppose to sent here. If that is the case then consider using a layout like in https://github.com/Ryochan7/DS4Windows/issues where general information is available at the top.

**Comment by Larsluph** [comment]
Hi,
Thanks for this request. Unfortunately, it currently is out of scope regarding RocketStats. It should be a completely new plugin's job.
