### ISSUE TITLE
Playing tournaments and ranked are treated as the same game mode

### ISSUE THREAD

**Issue by maggaou** [Lyliya/RocketStats#31]
It shouldn't be the case. After the 2v2 standard tournament, I want to start as fresh 0 wins + 0 losses when I go to play 2v2 standard ranked.

**Comment by Lyliya** [comment]
Hey @maggaou 👋

It's should be already doable, make sure you have checked the checkbox to differentiate playlists in the RocketStats settings menu. There are considered as different playlist from RocketLeague and Bakkesmod, and should start fresh every time you change playlist

**Comment by maggaou** [comment]
Hi. Can you point where that checkbox option is? Or do you mean drop down option under Mode in which case I should choose Gamemode or Always Gamemode?

**Comment by Larsluph** [comment]
That's it!
